image:
  file: .gitpod.Dockerfile

tasks:
    - name: dev env setup
      init: |
        cp ./dev-env/bash_aliases ~/.bash_aliases
        source ~/.bashrc

vscode:
  extensions:
    - ms-python.python
    - ms-python.debugpy
    - kevinrose.vsc-python-indent
    - wholroyd.jinja 
    - donjayamanne.python-extension-pack
    - donjayamanne.python-environment-manager
    - njpwerner.autodocstring
    - batisteo.vscode-django
